### ISSUE TITLE
How to fix this?

### ISSUE THREAD

**Issue by taeyunie** [fcamarlinghi/cepy#1]
**Error: Cannot find module './distrib/cepy.certificate.js'**

i found same issue. https://github.com/fcamarlinghi/expresso/issues/1

followed that, but i couldn't fix it. please explain me for detailed information.

i'm newb in npm.

**Comment by fcamarlinghi** [comment]
Hi, sorry if took this long to get back to you. The only workaround to fix this problem is the same explained in the Github issue you linked to. You need to create a text file called *cepy.certificate.js* in the `<project_root>/scripts/distrib/` folder, and add the following content to it:

``` js
module.exports = {
    owner: 'Your name',
    file: 'scripts/distrib/cepy.certificate.p12',
    password: 'Your password',
};
```
You should replace 'Your name' and 'Your password' with a name and a password of your choice that will be used to generate the certificate needed to sign the extension package.

**Comment by fcamarlinghi** [comment]
Closing this since the step above is now outlined in the Expresso readme.
